Repository vshn/component-appcat, pull requests merged in 2022-12, with the labels that each got.

#49 Add Composite and Composition for Kafka
  .github/workflows/packages.yaml
  apis/v1/dbaas_exoscale_kafka.go
  docs/modules/ROOT/pages/references/composite/dbaas/exoscale/kafka.adoc
  docs/modules/ROOT/pages/references/composition/dbaas/exoscale/kafka.adoc
  docs/modules/ROOT/partials/nav.adoc
  packages/composite/dbaas/exoscale/kafka.yml
  packages/composition/dbaas/exoscale/kafka.yml
  packages/tests/composite-dbaas-kafka-exoscale.yml
  packages/tests/composition-dbaas-kafka-exoscale.yml
  packages/tests/golden/composite-dbaas-kafka-exoscale/appcat/appcat/clusterRoles.yaml
  packages/tests/golden/composite-dbaas-kafka-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-kafka-exoscale/appcat/apps/appcat.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/appcat/appcat/additionalResources.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/appcat/apps/appcat.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/apps/crossplane.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/00_namespace.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrole.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/deployment.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-allowed-provider-permissions.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrole.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-deployment.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-managed-clusterroles.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-serviceaccount.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/secret.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/service.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/serviceaccount.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/02_upgrade/00_upgrade.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/10_providers.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/20_monitoring.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/30_controller_configs.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/40_service_accounts.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/50_cluster_roles.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/60_cluster_role_bindings.yaml
  packages/tests/golden/composition-dbaas-kafka-exoscale/crossplane/crossplane/70_provider_configs.yaml
Labels: enhancement

#52 remove ca.crt from Exoscale DBaaS redis
  packages/composite/dbaas/exoscale/redis.yml
  packages/composition/dbaas/exoscale/redis.yml
  packages/tests/golden/composite-dbaas-redis-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composition-dbaas-redis-exoscale/appcat/appcat/compositions.yaml
Labels: change

#48 cloudscale metrics collector with k8s api support
  packages/composition/objectstorage/cloudscale.yml
  packages/tests/golden/composition-objectstorage-cloudscale/appcat/appcat/compositions.yaml
Labels: enhancement

#53 Update provider exoscale to v0.5.0
  packages/provider/exoscale.yml
  packages/tests/golden/provider-exoscale/crossplane/crossplane/10_providers.yaml
Labels: dependency

#55 Fix nested defaulting for XRDs
  apis/v1/dbaas_exoscale.go
  apis/v1/dbaas_exoscale_mysql.go
  apis/v1/dbaas_exoscale_postgresql.go
  apis/v1/dbaas_exoscale_redis.go
  packages/composite/dbaas/exoscale/mysql.yml
  packages/composite/dbaas/exoscale/postgres.yml
  packages/composite/dbaas/exoscale/redis.yml
  packages/tests/golden/composite-dbaas-mysql-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-redis-exoscale/appcat/appcat/composites.yaml
Labels: bug

#54 remove namespace observer exoscale
  packages/composition/dbaas/exoscale/kafka.yml
  packages/composition/dbaas/exoscale/mysql.yml
  packages/composition/dbaas/exoscale/postgres.yml
  packages/composition/dbaas/exoscale/redis.yml
  packages/composition/objectstorage/exoscale.yml
  packages/tests/golden/composition-dbaas-kafka-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-mysql-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-redis-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-objectstorage-exoscale/appcat/appcat/compositions.yaml
Labels: enhancement

#56 Add Composite and Composition for OpenSearch
  Makefile
  apis/v1/dbaas_exoscale_opensearch.go
  packages/composite/dbaas/exoscale/opensearch.yml
  packages/composition/dbaas/exoscale/opensearch.yml
  packages/tests/composite-dbaas-opensearch-exoscale.yml
  packages/tests/composition-dbaas-opensearch-exoscale.yml
  packages/tests/golden/composite-dbaas-opensearch-exoscale/appcat/appcat/clusterRoles.yaml
  packages/tests/golden/composite-dbaas-opensearch-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-opensearch-exoscale/appcat/apps/appcat.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/appcat/appcat/additionalResources.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/appcat/apps/appcat.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/apps/crossplane.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/00_namespace.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrole.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/deployment.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-allowed-provider-permissions.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrole.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-deployment.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-managed-clusterroles.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-serviceaccount.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/secret.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/service.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/serviceaccount.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/02_upgrade/00_upgrade.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/10_providers.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/20_monitoring.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/30_controller_configs.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/40_service_accounts.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/50_cluster_roles.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/60_cluster_role_bindings.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/crossplane/crossplane/70_provider_configs.yaml
Labels: enhancement

#59 Fix default values in Exoscale DBAAS composites
  apis/exoscale/v1/dbaas_exoscale_mysql.go
  apis/exoscale/v1/dbaas_exoscale_postgresql.go
  packages/composite/dbaas/exoscale/mysql.yml
  packages/composite/dbaas/exoscale/postgres.yml
  packages/tests/golden/composite-dbaas-mysql-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/appcat/composites.yaml
Labels: bug

#60 fixing missing default Kafka version
  apis/exoscale/v1/dbaas_exoscale_kafka.go
  packages/composite/dbaas/exoscale/kafka.yml
  packages/tests/golden/composite-dbaas-kafka-exoscale/appcat/appcat/composites.yaml
Labels: bug

#63 refactoring Opensearch -> OpenSearch AND adding 2 new fields to conne…
  apis/exoscale/v1/dbaas_exoscale_opensearch.go
  docs/modules/ROOT/pages/references/composition/dbaas/exoscale/opensearch.adoc
  packages/composite/dbaas/exoscale/opensearch.yml
  packages/composition/dbaas/exoscale/opensearch.yml
  packages/provider/exoscale.yml
  packages/tests/golden/composite-dbaas-opensearch-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composition-dbaas-opensearch-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/provider-exoscale/crossplane/crossplane/10_providers.yaml
Labels: change

#64 upgrade provider exoscale version
  packages/provider/exoscale.yml
  packages/tests/golden/provider-exoscale/crossplane/crossplane/10_providers.yaml
Labels: bug
