Repository vshn/component-appcat, pull requests merged in 2022-10, with the labels that each got.

#31 Improve testing experience with Kuttl
  .gitignore
  README.md
  tests/kuttl/cloudscale-status-test/01-install-claim.yaml
  tests/kuttl/cloudscale-status-test/02-assert-claim-status.yaml
  tests/kuttl/cloudscale-status-test/03-delete.yaml
  tests/kuttl/cloudscale-status-test/04-delete.yaml
  tests/kuttl/exoscale-status-test/01-install-claim.yaml
  tests/kuttl/exoscale-status-test/02-assert-claim-status.yaml
  tests/kuttl/exoscale-status-test/03-delete.yaml
  tests/kuttl/exoscale-status-test/04-delete.yaml
  tests/kuttl/kuttl-test.yaml
  tests/kuttl/patch-object.sh
  tests/local.mk
Labels: change

#33 Create XRDs using Kubebuilder
  .github/workflows/lint.yaml
  .gitignore
  Makefile
  README.md
  apis/generate.mk
  apis/go.mod
  apis/go.sum
  apis/tools.go
  apis/v1/conditions.go
  apis/v1/groupversion_info.go
  apis/v1/objectstorage_types.go
  packages/composite/objectstorage.yml
  packages/tests/golden/composite-objectstorage-cloudscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-objectstorage-exoscale/appcat/appcat/composites.yaml
  tests/kuttl/cloudscale-status-test/00-install-cloudscale-composite.yaml
  tests/kuttl/exoscale-status-test/00-install-exoscale-composite.yaml
  tests/local.mk
Labels: change

#34 Remove extra generated XRD fields
  apis/v1/objectstorage_types.go
  packages/composite/objectstorage.yml
  packages/tests/golden/composite-objectstorage-cloudscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-objectstorage-exoscale/appcat/appcat/composites.yaml
  tests/kuttl/cloudscale-status-test/00-install-cloudscale-composite.yaml
  tests/kuttl/exoscale-status-test/00-install-exoscale-composite.yaml
Labels: bug

#32 Add PostgreSQL composition
  .github/workflows/packages.yaml
  docs/modules/ROOT/pages/references/composition/dbaas/exoscale/common.adoc
  docs/modules/ROOT/pages/references/composition/dbaas/exoscale/postgres.adoc
  docs/modules/ROOT/partials/nav.adoc
  packages/composition/dbaas/exoscale/common.yml
  packages/composition/dbaas/exoscale/postgres.yml
  packages/tests/composition-dbaas-postgres-exoscale.yml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/appcat/additionalResources.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/appcat/secrets.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/apps/appcat.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/apps/crossplane.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/00_namespace.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrole.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/deployment.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-allowed-provider-permissions.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrole.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-clusterrolebinding.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-deployment.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-managed-clusterroles.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/rbac-manager-serviceaccount.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/secret.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/service.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/01_helmchart/crossplane/templates/serviceaccount.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/02_upgrade/00_upgrade.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/10_providers.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/20_monitoring.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/30_controller_configs.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/40_service_accounts.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/50_cluster_roles.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/60_cluster_role_bindings.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/crossplane/crossplane/70_provider_configs.yaml
Labels: enhancement

#29 Add endpoint to Bucket status
  packages/composite/objectstorage.yml
  packages/composition/objectstorage/cloudscale.yml
  packages/composition/objectstorage/exoscale.yml
  packages/provider/cloudscale.yml
  packages/provider/exoscale.yml
  packages/tests/golden/composite-objectstorage-cloudscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-objectstorage-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composition-objectstorage-cloudscale/appcat/appcat/compositions.yaml
  packages/tests/golden/composition-objectstorage-exoscale/appcat/appcat/compositions.yaml
  packages/tests/golden/provider-cloudscale/crossplane/crossplane/10_providers.yaml
  packages/tests/golden/provider-exoscale/crossplane/crossplane/10_providers.yaml
  tests/kuttl/cloudscale-status-test/00-install-cloudscale-composite.yaml
  tests/kuttl/cloudscale-status-test/00-install-cloudscale-composition.yaml
  tests/kuttl/cloudscale-status-test/01-assert-managed-resources.yaml
  tests/kuttl/exoscale-status-test/00-install-exoscale-composite.yaml
  tests/kuttl/exoscale-status-test/00-install-exoscale-composition.yaml
  tests/kuttl/exoscale-status-test/01-assert-managed-resources.yaml
Labels: enhancement

#36 Add ExoscalePostgreSQL composite
  docs/modules/ROOT/pages/references/composite/dbaas/exoscale/postgres.adoc
  docs/modules/ROOT/partials/nav.adoc
  packages/composite/dbaas/exoscale/postgres.yml
  packages/tests/composite-dbaas-postgres-exoscale.yml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/appcat/clusterRoles.yaml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/apps/appcat.yaml
Labels: enhancement

#37 Add defaults to the postgres exoscale XRD
  packages/composite/dbaas/exoscale/postgres.yml
  packages/composition/dbaas/exoscale/postgres.yml
  packages/tests/golden/composite-dbaas-postgres-exoscale/appcat/appcat/composites.yaml
  packages/tests/golden/composition-dbaas-postgres-exoscale/appcat/appcat/compositions.yaml
Labels: change
