Repository vshn/component-appcat, pull requests merged in 2023-02, with the labels that each got.

#89 Update provider-exoscale to v0.9.0
  class/defaults.yml
  tests/golden/exoscale/appcat/appcat/10_provider_exoscale.yaml
  tests/golden/openshift/appcat/appcat/10_provider_exoscale.yaml
Labels: dependency

#91 Adding CR's status fields to XRD
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: enhancement

#93 Don't pass the annotations and labels to the managed resources
  component/exoscale_kafka.jsonnet
  component/exoscale_mysql.jsonnet
  component/exoscale_opensearch.jsonnet
  component/exoscale_postgres.jsonnet
  component/exoscale_redis.jsonnet
  component/objectstorage.jsonnet
  component/vshn_postgres.jsonnet
  lib/appcat-compositions.libsonnet
  tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/openshift/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: bug

#88 Add VSHNManaged Redis support
  apis/vshn/v1/dbaas_vshn_redis.go
  class/appcat.yml
  class/defaults.yml
  component/provider.jsonnet
  component/vshn_redis.jsonnet
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  docs/modules/ROOT/pages/references/services-vshn.adoc
  lib/appcat-compositions.libsonnet
  tests/golden/vshn/appcat/appcat/10_provider_helm.yaml
  tests/golden/vshn/appcat/appcat/20_rbac_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/vshn.yml
Labels: enhancement

#94 Adjust requests to the fair use ratio
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  pod.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: enhancement

#95 TLS support for PostgreSQL managed by VSHN
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/provider.jsonnet
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: enhancement

#97 Local dev S3 composition
  apis/vshn/v1/dbaas_vshn_redis.go
  component/provider.jsonnet
  dev/component/objectstorage.jsonnet
  tests/golden/vshn/appcat/appcat/20_rbac_helm_provider_dev.yaml
  tests/golden/vshn/appcat/appcat/20_rbac_objectstorage.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_objectstorage.yaml
  tests/golden/vshn/appcat/appcat/21_composition_objectstorage_minio_dev.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/vshn.yml
Labels: enhancement

#96 Add feature to specify a nodeSelector for the postgreSQL instance
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: enhancement

#101 Fix defaults to remove ArgoCD diff
  component/vshn_postgres.jsonnet
  lib/appcat-compositions.libsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: bug

#99 Add apiserver
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/appcat.yml
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  component/common.libsonnet
  docs/modules/ROOT/pages/references/appcat-apiserver.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/apiserver.yml
  tests/golden/apiserver/appcat/appcat/10_clusterrole_view.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/20_certs.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_service.yaml
  tests/golden/apiserver/appcat/apps/appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_service.yaml
  tests/golden/defaults/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/defaults/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/defaults/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/defaults/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_service.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_service.yaml
  tests/golden/openshift/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/openshift/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/openshift/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/openshift/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/vshn/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_service.yaml
Labels: enhancement

#102 Add TLS support for Redis by VSHN
  apis/vshn/v1/dbaas_vshn_redis.go
  component/vshn_redis.jsonnet
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement
