Repository vshn/component-appcat, pull requests merged in 2023-03, with the labels that each got.

#106 Allow setting resource requests and limits separately for VshnPostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#107 Add VSHNPostgreSQLList implementation
  apis/generate.mk
  apis/go.mod
  apis/go.sum
  apis/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/zz_generated.deepcopy.go
  tests/golden/apiserver/appcat/appcat/apiserver/20_certs.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#109 Bump apiserver version
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: enhancement, dependency

#111 Add patch maintenance script for PostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  component/provider.jsonnet
  component/scripts/pg-maintenance.sh
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/defaults/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/vshn/appcat/appcat/apiserver/20_certs.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/vshn.yml
Labels: enhancement

#113 Add instance namespace permissions
  component/main.jsonnet
  component/provider.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  lib/appcat-compositions.libsonnet
  tests/golden/apiserver/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/cloudscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/defaults/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/exoscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement

#115 Fix RBAC not being applied properly
  component/provider.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
Labels: bug

#116 Add instanceNamespace to redis as well
  apis/vshn/v1/dbaas_vshn_redis.go
  component/vshn_redis.jsonnet
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement

#105 Disable RBAC creation by appuio-cloud-agent
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: change

#118 Add Prometheus rule for storage
  component/provider.jsonnet
  component/vshn_postgres.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#119 Add memory alerts
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#117 Reduce sidecar resource requests
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: change

#122 Add option to specify NodeSelector for redis by VSHN
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/zz_generated.deepcopy.go
  component/vshn_redis.jsonnet
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement

#114 Add plans for PostgreSQL by VSHN
  apis/vshn/v1/dbaas_vshn_postgresql.go
  class/defaults.yml
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  docs/modules/ROOT/pages/references/services-vshn.adoc
  lib/appcat-compositions.libsonnet
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/vshn.yml
Labels: enhancement

#120 Add plans for redis by VSHN
  apis/vshn/v1/dbaas_vshn_redis.go
  class/defaults.yml
  component/common.libsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  component/xrds.libsonnet
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  docs/modules/ROOT/pages/references/services-vshn.adoc
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/vshn.yml
Labels: enhancement

#123 Bump appcat apiserver to v0.2.2
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: dependency

#121 Add alert for postgresql connections
  component/provider.jsonnet
  component/vshn_postgres.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#126 Fix ExoscaleOpenSearch root object
  apis/exoscale/v1/dbaas_exoscale_opensearch.go
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  tests/golden/exoscale/appcat/appcat/20_xrd_exoscale_opensearch.yaml
  tests/golden/openshift/appcat/appcat/20_xrd_exoscale_opensearch.yaml
Labels: bug, documentation

#127 Add `writeConnectionSecretToRef` to Go types
  apis/exoscale/v1/dbaas_exoscale_kafka.go
  apis/exoscale/v1/dbaas_exoscale_mysql.go
  apis/exoscale/v1/dbaas_exoscale_opensearch.go
  apis/exoscale/v1/dbaas_exoscale_postgresql.go
  apis/exoscale/v1/dbaas_exoscale_redis.go
  apis/v1/objectreference.go
  apis/v1/objectstorage_types.go
  apis/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/zz_generated.deepcopy.go
  component/xrds.libsonnet
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
Labels: change

#128 Update provider exoscale to v0.9.2
  class/defaults.yml
  tests/golden/exoscale/appcat/appcat/10_provider_exoscale.yaml
  tests/golden/openshift/appcat/appcat/10_provider_exoscale.yaml
Labels: bug

#130 Make composition function compatible
  component/vshn_postgres.jsonnet
  lib/appcat-compositions.libsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement
