Repository vshn/component-appcat, pull requests merged in 2023-07, with the labels that each got.

#175 Fix user permission in DB namespace
  component/main.jsonnet
  tests/golden/apiserver/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/cloudscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/controllers/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/defaults/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/exoscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/openshift/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/vshn/appcat/appcat/10_clusterrole_services_read.yaml
Labels: bug

#172 Add prometheus rule to aggregate AppCat billing data per cluster
  class/defaults.yml
  component/main.jsonnet
  component/promql/appcat.promql
  docs/modules/ROOT/pages/how-tos/billing.adoc
  docs/modules/ROOT/pages/references/component-parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/apiserver/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/apiserver/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/cloudscale/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/cloudscale/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/controllers/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/controllers/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/defaults/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/defaults/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/exoscale/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/exoscale/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/vshn/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/vshn/appcat/appcat/10_appcat_recording_rule.yaml
Labels: enhancement

#176 Explicitly allow provider kubernetes to bind `appcat:services:read`
  component/provider.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
Labels: bug

#177 Fix rbac rules for maintenance being created on non vshn services
  class/appcat.yml
  component/vshn_postgres.jsonnet
  component/vshn_services.jsonnet
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/vshn/appcat/appcat/10_namespace_vshn_control.yaml
Labels: bug

#179 Add postgres SLA
  class/defaults.yml
  component/appcat_sla_reporter.jsonnet
  component/common.libsonnet
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/22_prom_rule_sla_postgres.yaml
Labels: enhancement

#181 Bump AppCat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#182 Add repack extension to vshn postgres
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#183 Update SGDbOps resources
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug

#185 Add missing project permissions on appcat service namespace
  component/main.jsonnet
  tests/golden/apiserver/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/cloudscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/controllers/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/defaults/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/exoscale/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/openshift/appcat/appcat/10_clusterrole_services_read.yaml
  tests/golden/vshn/appcat/appcat/10_clusterrole_services_read.yaml
Labels: bug

#184 Add extension support
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#186 Bump version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#187 Add SA, Clusterrole and Clusterrolebinding for redis restores
  component/provider.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/20_role_vshn_redisrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: change

#188 Enable HA deployment of PostgreSQL
  class/appcat.yml
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#190 Update provider kubernetes and helm to latest version
  class/defaults.yml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_helm.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
Labels: dependency

#192 Add rbac rule for redis restore to be able to create events
  component/vshn_redis.jsonnet
  tests/golden/vshn/appcat/appcat/20_role_vshn_redisrestore.yaml
Labels: enhancement

#193 Bump appcat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: change

#194 Update AppCat to fix SLI Exporter bug
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug

#195 Fix redis backups API server display bug
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_basic_users.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug, dependency
