Repository vshn/component-appcat, pull requests merged in 2023-08, with the labels that each got.

#191 Adding necessary field names to handle external IPs in connection secret
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/vshn.yml
Labels: change

#198 Bump appcat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#202 bumping appcat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#199 Add support for guaranteed availability
  class/defaults.yml
  component/slos.libsonnet
  component/vshn_postgres.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#204 fixing issue with insecure Redis certificates
  component/vshn_redis.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: enhancement

#205 Bump appcat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#207 Increasing the sts resizer's resources
  class/defaults.yml
  component/statefuleset-resize-controller.jsonnet
  tests/golden/vshn/appcat/appcat/controllers/sts-resizer/10_deployment.yaml
Labels: bug

#203 Add webhook support for the controller
  class/appcat.yml
  class/defaults.yml
  component/appcat_controller.jsonnet
  component/appcat_controller_postgres.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_cluster_role.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_cluster_role_binding.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_pg_webhooks.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_redis_webhooks.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_role_binding_leader_election.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_role_leader_election.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhook_certificate.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhook_issuer.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhook_service.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/20_service_account.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/10_namespace.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/10_role_binding_leader_election.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/20_service_account.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/vshn/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/20_plans_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_cluster_role.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_cluster_role_binding.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_pg_webhooks.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_redis_webhooks.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_role_binding_leader_election.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_role_leader_election.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhook_certificate.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhook_issuer.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhook_service.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/20_service_account.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/10_namespace.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/10_role_binding_leader_election.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/20_service_account.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/vshn.yml
Labels: enhancement

#208 Adding SLO rule for VSHNRedis
  class/defaults.yml
  component/appcat_sli_exporter.jsonnet
  component/main.jsonnet
  component/slos.libsonnet
  component/vshn_redis.jsonnet
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#209 moving image asset to correct directory
  docs/modules/ROOT/images/crossplane-secrets.png
Labels: documentation

#213 Fix renovate config
  renovate.json
Labels: bug

#211 Update Helm release redis to v17.7.1
  class/defaults.yml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: dependency
