Repository vshn/component-appcat, pull requests merged in 2023-06, with the labels that each got.

#157 Migrating maintenance logic to comp-func
  class/defaults.yml
  component/provider.jsonnet
  component/vshn_postgres.jsonnet
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/vshn.yml
Labels: enhancement

#160 Bump appcat
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#162 Fixes for ArgoCD
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: bug

#158 Switch miniodev to comp-function
  dev/component/objectstorage.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_objectstorage_minio_dev.yaml
Labels: enhancement

#163 Escape tags, so they support valid branch names
  component/appcat_apiserver.jsonnet
  component/appcat_controller_postgres.jsonnet
  component/appcat_sli_exporter.jsonnet
  component/common.libsonnet
  component/vshn_postgres.jsonnet
Labels: enhancement

#155 Adding possibility to send some alerts to customers via mailgun
  class/defaults.yml
  component/main.jsonnet
  component/vshn_postgres.jsonnet
  docs/modules/ROOT/pages/references/services-vshn.adoc
  tests/golden/apiserver/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/controllers/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/vshn/appcat/appcat/10_mailgun_secret.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/vshn.yml
Labels: enhancement

#164 Add SLA reporter cronjob
  class/appcat.yml
  class/defaults.yml
  component/appcat_sla_reporter.jsonnet
  component/main.jsonnet
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/slo-parameters.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/defaults/appcat/appcat/sla_reporter/02_object_bucket.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-proxy-rolebinding.yaml
  tests/golden/openshift/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/openshift/appcat/appcat/sla_reporter/02_object_bucket.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-proxy-rolebinding.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/02_object_bucket.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrolebinding_appcat-sliexporter-proxy-rolebinding.yaml
  tests/vshn.yml
Labels: enhancement

#165 Fix wrong parameter to enable SLA reporter
  component/appcat_sla_reporter.jsonnet
  tests/golden/defaults/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/defaults/appcat/appcat/sla_reporter/02_object_bucket.yaml
  tests/golden/openshift/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/openshift/appcat/appcat/sla_reporter/02_object_bucket.yaml
Labels: bug

#167 Add Redis backups
  class/defaults.yml
  component/provider.jsonnet
  component/vshn_redis.jsonnet
  docs/modules/ROOT/pages/how-tos/redisrestore.adoc
  docs/modules/ROOT/pages/references/services-vshn.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#168 Bump AppCAt
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#170 Add Redis backup listing
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/10_apiserver_envs.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_apiserver_envs.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#169 Give option to disable e-mail alerting
  class/defaults.yml
  component/main.jsonnet
  component/vshn_postgres.jsonnet
  docs/modules/ROOT/pages/references/services-vshn.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/vshn.yml
Labels: enhancement

#173 Add maintenance job
  class/appcat.yml
  class/defaults.yml
  component/vshn_helm_based_service.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  docs/modules/ROOT/pages/references/component-parameters.adoc
  docs/modules/ROOT/pages/references/services-vshn.adoc
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/apiserver/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/cloudscale/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/controllers/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/defaults/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/exoscale/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/vshn/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/vshn/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#174 Add option to define namespace labels and annotations
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  component/appcat_controller_postgres.jsonnet
  component/appcat_sli_exporter.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/appcat-apiserver.adoc
  docs/modules/ROOT/pages/references/appcat-postgres-controller.adoc
  docs/modules/ROOT/pages/references/component-parameters.adoc
  docs/modules/ROOT/pages/references/slo-parameters.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/10_namespace.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_namespace.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/v1_namespace_appcat-slos.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/10_namespace.yaml
  tests/openshift.yml
Labels: enhancement
