Repository vshn/component-appcat, pull requests merged in 2023-04, with the labels that each got.

#132 Fixing race condition in first reconciliation
  component/vshn_postgres.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: bug

#136 Fix invalid composition naming
  component/vshn_redis.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: bug

#135 Fix outdated user docs url
  component/common.libsonnet
  tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/openshift/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: documentation

#139 Add Namespace field in objectreference
  apis/v1/objectreference.go
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
Labels: bug

#124 Add user alerting to PostgreSQL
  apis/generate.mk
  apis/go.mod
  apis/go.sum
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  component/provider.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
Labels: enhancement

#129 Add feature to allow using encrypted PVCs for VshnPostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  component/vshn_postgres.jsonnet
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  lib/appcat-compositions.libsonnet
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#141 Add randomized default maintenance and backup schedules for PostgreSQL by VSHN
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
Labels: enhancement
