Repository vshn/component-appcat, pull requests merged in 2023-05, with the labels that each got.

#137 Add UpdateStrategy to VSHNPostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
Labels: enhancement

#144 Add new billing label to postgresql and redis
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: change

#145 Fix error in VSHNPostgreSQL CRD description
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
Labels: bug

#147 Handle API server cert via cert-manager
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/20_certs.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/31_api_certificate.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/31_api_issuer.yaml
  tests/golden/vshn/appcat/appcat/apiserver/20_certs.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/31_api_certificate.yaml
  tests/golden/vshn/appcat/appcat/apiserver/31_api_issuer.yaml
  tests/vshn.yml
Labels: enhancement

#142 Add SLO for PostgreSQL by VSHN
  .gitignore
  class/appcat.yml
  class/defaults.yml
  component/main.jsonnet
  component/slos.libsonnet
  component/sloth-input.jsonnet
  docs/modules/ROOT/pages/references/slo-parameters.adoc
  docs/modules/ROOT/pages/runbooks/vshn-postgresql.adoc
  docs/modules/ROOT/partials/nav.adoc
  run-sloth
  tests/golden/vshn/appcat/appcat/90_slo_vshn_postgresql.yaml
Labels: enhancement

#150 Bump API server image
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/10_cluster_role.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/10_cluster_role.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
Labels: dependency

#149 Add OpenShift templates to AppCat
  Makefile.vars.mk
  apis/exoscale/v1/dbaas_exoscale_kafka.go
  component/common.libsonnet
  component/exoscale_kafka.jsonnet
  component/exoscale_mysql.jsonnet
  component/exoscale_opensearch.jsonnet
  component/exoscale_postgres.jsonnet
  component/exoscale_redis.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  docs/modules/ROOT/pages/explanations/add-to-openshift-catalog.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/exoscale/appcat/appcat/20_xrd_exoscale_kafka.yaml
  tests/golden/openshift/appcat/appcat/20_xrd_exoscale_kafka.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_kafka_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_mysql_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_opensearch_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_postgresql_exoscale.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_redis_exoscale.yaml
Labels: enhancement

#153 Add plans metadata to the compositons
  Makefile
  class/defaults.yml
  component/common.libsonnet
  component/exoscale-plans/grafana.json
  component/exoscale-plans/kafka.json
  component/exoscale-plans/mysql.json
  component/exoscale-plans/opensearch.json
  component/exoscale-plans/pg.json
  component/exoscale-plans/redis.json
  component/exoscale_kafka.jsonnet
  component/exoscale_mysql.jsonnet
  component/exoscale_opensearch.jsonnet
  component/exoscale_postgres.jsonnet
  component/exoscale_redis.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  dev/scripts/exoscale-plans/go.mod
  dev/scripts/exoscale-plans/go.sum
  dev/scripts/exoscale-plans/main.go
  docs/modules/ROOT/pages/explanations/exoscale-plans.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_kafka.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_mysql.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_opensearch.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_exoscale_redis.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/postgres/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement
