Repository vshn/component-appcat, pull requests merged in 2023-12, with the labels that each got.

#269 Fix duplicate finalizers
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#263 Add composition for MariaDB service
  component/class/appcat.yml
  component/class/defaults.yml
  component/component/main.jsonnet
  component/component/provider.jsonnet
  component/component/slos.libsonnet
  component/component/statefuleset-resize-controller.jsonnet
  component/component/vshn_appcat_services.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/10_apiserver_envs.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_helm.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/10_apiserver_envs.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/90_slo_vshn_minio_ha.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_helm.yaml
  component/tests/golden/vshn/appcat/appcat/20_plans_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/20_rbac_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/20_rbac_vshn_redis_metrics_servicemonitor.yaml
  component/tests/golden/vshn/appcat/appcat/20_role_vshn_mariadb_restore.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/10_apiserver_envs.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/sts-resizer/20_rbac_resize_job.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_mariadb_ha.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis_ha.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  docs/modules/ROOT/pages/runbooks/vshn-helm-debugging-partial.adoc
  docs/modules/ROOT/pages/runbooks/vshn-mariadb.adoc
  docs/modules/ROOT/pages/runbooks/vshn-minio.adoc
  docs/modules/ROOT/pages/runbooks/vshn-redis.adoc
  docs/modules/ROOT/partials/nav.adoc
  package/main.yaml
Labels: enhancement

#271 Fix SLI Proper bug
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: breaking

#276 Bump Appcat version
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement, dependency

#273 Remove namespace and rbac p&t (moved to functionIO)
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: bug

#277 Bump version
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#272 Add billing for Odoo 16
  component/class/appcat.yml
  component/class/defaults.yml
  component/component/billing.jsonnet
  component/component/billing_alerts.libsonnet
  component/component/billing_cronjob.libsonnet
  component/component/billing_netpol.libsonnet
  component/component/main.jsonnet
  component/component/promql/metering_cloud.promql
  component/component/promql/metering_managed.promql
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/controllers/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/defaults/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/exoscale/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/minio/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/openshift/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/vshn/appcat/appcat/10_appcat_legacy_billing_recording_rule.yaml
  component/tests/golden/vshn/appcat/appcat/10_appcat_metering_recording_rule.yaml
  component/tests/golden/vshn/appcat/appcat/10_mock_org_info.yaml
  component/tests/golden/vshn/appcat/appcat/billing/00_namespace.yaml
  component/tests/golden/vshn/appcat/appcat/billing/10_odoo_secret.yaml
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
  component/tests/golden/vshn/appcat/appcat/billing/50_alerts.yaml
  component/tests/vshn.yml
  docs/modules/ROOT/pages/explanations/billing.adoc
  package/Makefile
  package/Makefile.vars.mk
  package/main.yaml
Labels: enhancement

#278 Don't import appuio-reporting
  package/main.yaml
Labels: bug

#279 Add claim name label to the instance namespaces
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#280 Document billing alert
  component/class/defaults.yml
  component/tests/golden/vshn/appcat/appcat/billing/50_alerts.yaml
  docs/modules/ROOT/pages/runbooks/vshn-billing.adoc
Labels: documentation

#281 Reduce collected metrics from pg exporter
  component/component/vshn_postgres.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: bug

#282 Ignore integration metrics looking up sales order
  component/class/defaults.yml
  component/component/billing.jsonnet
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
  component/tests/vshn.yml
Labels: bug

#283 Don't create ns for billing
  component/component/billing.jsonnet
  component/tests/golden/vshn/appcat/appcat/billing/00_namespace.yaml
Labels: bug

#284 Bummp APPUiO Reporting
  component/class/defaults.yml
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
Labels: enhancement

#285 Bump billing-collector version
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency

#286 Set proper Zone or Cluster description for odoo billing export
  component/class/defaults.yml
  component/component/billing.jsonnet
  component/component/cloud_billing.jsonnet
  component/component/common.libsonnet
  component/tests/apiserver.yml
  component/tests/cloudscale-metrics-collector-cloud.yml
  component/tests/cloudscale-metrics-collector-managed.yml
  component/tests/cloudscale.yml
  component/tests/controllers.yml
  component/tests/defaults.yml
  component/tests/exoscale-metrics-collector-cloud.yml
  component/tests/exoscale-metrics-collector-managed.yml
  component/tests/exoscale.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_cloudscale_configmap.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_cloudscale_configmap.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_configmap.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_object_storage_configmap.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_configmap.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_object_storage_configmap.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
  component/tests/minio.yml
  component/tests/openshift.yml
  component/tests/vshn.yml
Labels: bug

#287 Adjust instance_id to ensure it's unique across our systems
  component/component/billing.jsonnet
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
Labels: bug

#289 Bump billing collector version
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency

#290 Don't set cloudZone by default as this will break APPUiO Managed clusters
  component/class/defaults.yml
  component/tests/cloudscale-metrics-collector-cloud.yml
  component/tests/cloudscale-metrics-collector-managed.yml
  component/tests/exoscale-metrics-collector-cloud.yml
  component/tests/exoscale-metrics-collector-managed.yml
  component/tests/vshn.yml
Labels: bug

#291 Bump billing collector version
  .github/workflows/component-test.yaml
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency

#292 Fix vshn appcat reporting time frame
  component/component/billing.jsonnet
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
Labels: bug

#293 Fix missing closing quote
  component/component/billing.jsonnet
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
Labels: bug
