Repository vshn/component-appcat, pull requests merged in 2023-10, with the labels that each got.

#237 Add redis sla reporting and fix non-working maintenance exclusion
  class/defaults.yml
  component/main.jsonnet
  component/slos.libsonnet
  component/vshn_redis.jsonnet
  tests/golden/apiserver/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/cloudscale/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/controllers/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/minio/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_appcat_maintenance_recording_rule.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#235 Enable resource limits for sidecars and set sensible values
  component/class/defaults.yml
  component/component/vshn_postgres.jsonnet
  component/tests/golden/vshn/appcat/appcat/20_plans_vshn_postgresql.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: bug

#240 Use Github action PAT to push to master
  .github/workflows/release.yaml
Labels: change

#242 Bump appcat image version
  package/main.yaml
Labels: change

#241 disable certificates verification in redis metrics exporter
  component/component/vshn_redis.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: bug, enhancement

#246 Bump provider exoscale version
  component/class/defaults.yml
  component/tests/exoscale.yml
  component/tests/golden/exoscale/appcat/appcat/10_provider_exoscale.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_kafka.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_mysql.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_opensearch.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_postgres.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_redis.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_exoscale.yaml
Labels: bug

#247 add liveness and readiness probes to appcat apiserver
  component/component/appcat_apiserver.jsonnet
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: enhancement

#248 Add RBAC rules for minio metrics
  .gitignore
  component/class/defaults.yml
  component/component/provider.jsonnet
  component/tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  package/main.yaml
Labels: enhancement

#249 Add Redis alerting
  component/class/defaults.yml
  component/component/main.jsonnet
  component/component/slos.libsonnet
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis_ha.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#251 Fix restore operation not working for PostgreSQL by VSHN
  component/component/vshn_postgres.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: bug

#252 Add note about the default Minio instance
  docs/modules/ROOT/pages/explanations/minio.adoc
Labels: documentation
