Repository vshn/component-appcat, pull requests merged in 2023-09, with the labels that each got.

#217 Add network policy to sla reporter
  class/defaults.yml
  component/appcat_sla_reporter.jsonnet
  docs/modules/ROOT/pages/references/slo-parameters.adoc
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/03_network_policy.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/vshn.yml
Labels: bug

#215 adding replication alerting
  component/vshn_postgres.jsonnet
  docs/modules/ROOT/pages/runbooks/vshn-postgresql.adoc
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
Labels: enhancement

#218 Add provider-minio
  class/defaults.yml
  component/provider.jsonnet
  tests/golden/vshn/appcat/appcat/10_provider_minio.yaml
  tests/vshn.yml
Labels: enhancement

#225 Separate API Server image
  class/appcat.yml
  class/defaults.yml
  component/appcat_apiserver.jsonnet
  component/common.libsonnet
  tests/golden/apiserver/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_apiserver_envs.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_binding.yaml
  tests/golden/vshn/appcat/appcat/apiserver/10_namespace.yaml
  tests/golden/vshn/appcat/appcat/apiserver/20_service_account.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_api_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_service.yaml
  tests/golden/vshn/appcat/appcat/apiserver/31_api_certificate.yaml
  tests/golden/vshn/appcat/appcat/apiserver/31_api_issuer.yaml
  tests/vshn.yml
Labels: enhancement

#229 Generate a valid `kustomization.yaml` when SLOs are disabled
  component/appcat_sli_exporter.jsonnet
Labels: bug

#230 Add additional release permissions
  class/defaults.yml
  component/vshn_minio.jsonnet
  component/vshn_services.jsonnet
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/minio/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/minio/appcat/appcat/20_xrd_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_objectstorage_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/22_minio_instances.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/vshn.yml
Labels: enhancement

#232 Switching to composite
  class/defaults.yml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
Labels: enhancement

#231 Consider maintenance in PostgreSQL and Redis alerts.
  class/defaults.yml
  component/main.jsonnet
  component/slos.libsonnet
  tests/golden/apiserver/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/cloudscale/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/controllers/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/minio/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_appcat_recording_rule.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/vshn.yml
Labels: enhancement

#234 Patch bucketdeletionpolicy
  class/defaults.yml
  component/objectstorage.jsonnet
  tests/golden/cloudscale/appcat/appcat/20_xrd_objectstorage.yaml
  tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/20_xrd_objectstorage.yaml
  tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/20_xrd_objectstorage.yaml
  tests/golden/openshift/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_objectstorage.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#228 Add sidecar resources for calculating quota
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug

#236 Update ghcr.io/vshn/provider-exoscale/provider Docker tag to v0.10.3
  class/defaults.yml
  tests/golden/exoscale/appcat/appcat/10_provider_exoscale.yaml
  tests/golden/openshift/appcat/appcat/10_provider_exoscale.yaml
Labels: dependency
