Repository vshn/component-appcat, pull requests merged in 2024-04, with the labels that each got.

#340 Remove LPG e2e test
  .github/workflows/e2e.yaml
Labels: bug

#341 Fix/postgresql exporter
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#342 Add Keycloak SLI Prober
  component/class/defaults.yml
  component/component/appcat_sli_exporter.jsonnet
  component/component/vshn_appcat_services.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  package/main.yaml
Labels: enhancement

#344 Add/keycloak metrics
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#348 Add OpenShift flag to all services
  component/class/defaults.yml
  component/component/provider.jsonnet
  component/component/vshn_minio.jsonnet
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#349 Update appcat version to v4.65.0
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#350 Add label selectors to webhooks
  component/component/appcat_controller.jsonnet
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhooks.yaml
Labels: bug

#351 Update component version in package to v2.37.2
  component/class/defaults.yml
  component/component/appcat_sli_exporter.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/rbac.authorization.k8s.io_v1_clusterrole_appcat-sliexporter-appcat-sli-exporter.yaml
  package/main.yaml
Labels: enhancement

#352 Reduce max pg name further
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug
