Repository vshn/component-appcat, pull requests merged in 2024-08, with the labels that each got.

#432 Add deletionProtection for ObjectBuckets
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/20_xrd_objectstorage.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/20_xrd_objectstorage.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/20_xrd_objectstorage.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_objectstorage.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/10_webhooks.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#434 Fix bucket name clashes by moving to comp functions
  component/class/defaults.yml
  component/component/objectstorage.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  package/main.yaml
Labels: bug

#435 Add Nextcloud backup
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#437 Add support for PostgreSQL 15 and 16 on Exoscale
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/20_xrd_exoscale_postgres.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/20_xrd_exoscale_postgres.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#438 Remove finalizers for Crossplane App
  package/main.yaml
Labels: change

#441 Add support for custom RBAC rules
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/20_xrd_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#443 Bump appcat version
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: dependency

#446 Add stackgres resource config
  class/defaults.yml
  component/vshn_postgres.jsonnet
  tests/golden/openshift/appcat/appcat/10_namespace_vshn_control.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_cluster_role_binding.yaml
  tests/golden/openshift/appcat/appcat/10_rbac_helm_service_maintenance_sa.yaml
  tests/golden/openshift/appcat/appcat/10_stackgres_openshift_operator_ns.yaml
  tests/golden/openshift/appcat/appcat/11_stackgres_openshift_operator.yaml
  tests/golden/openshift/appcat/appcat/12_stackgres_openshift_operator_netpol.yaml
  tests/golden/openshift/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/openshift/appcat/appcat/20_plans_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/20_rbac_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/20_rbac_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/20_role_vshn_postgresrestore.yaml
  tests/golden/openshift/appcat/appcat/20_role_vshn_redisrestore.yaml
  tests/golden/openshift/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_postgresql_vshn.yaml
  tests/golden/openshift/appcat/appcat/21_openshift_template_redis_vshn.yaml
  tests/golden/openshift/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/openshift/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/openshift/appcat/appcat/controllers/sts-resizer/10_binding.yaml
  tests/golden/openshift/appcat/appcat/controllers/sts-resizer/10_deployment.yaml
  tests/golden/openshift/appcat/appcat/controllers/sts-resizer/10_role.yaml
  tests/golden/openshift/appcat/appcat/controllers/sts-resizer/10_sa.yaml
  tests/golden/openshift/appcat/appcat/controllers/sts-resizer/20_rbac_resize_job.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_redis_ha.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/statefuleset-resize-controller.yaml
  tests/openshift.yml
Labels: enhancement

#447 Bump provider-kubernetes version
  class/defaults.yml
  tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/minio/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
Labels: dependency

#448 Fix pointer leaks by using generics
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug

#454 Fix cloud billing query
  Makefile.vars.mk
  component/billing.jsonnet
  tests/golden/billing/appcat/appcat/billing/11_backfill.yaml
Labels: bug

#455 Fix billing mimir source
  class/defaults.yml
  tests/golden/billing/appcat/appcat/billing/11_backfill.yaml
Labels: bug

#456 Fix mimir source billing
  class/defaults.yml
  component/billing.jsonnet
  tests/golden/billing/appcat/appcat/billing/11_backfill.yaml
Labels: bug
