Repository vshn/component-appcat, pull requests merged in 2024-06, with the labels that each got.

#374 Fix RBAC for controller and max connection alerts
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/10_cluster_role.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/10_cluster_role.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/10_cluster_role.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#372 Update of dependencies
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_helm.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_helm.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_minio.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#376 Explicitly set the image again
  package/main.yaml
Labels: bug

#373 Event forwarding for external object storage
  component/class/defaults.yml
  component/component/objectstorage.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_objectstorage_exoscale.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement

#375 Rename Keycloak's restore service account
  component/class/defaults.yml
  component/tests/golden/vshn/appcat/appcat/20_role_vshn_keycloak_restore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
Labels: bug

#380 Adding VSHNMinio user alerting
  component/class/defaults.yml
  component/component/vshn_minio.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/20_xrd_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#370 Migrate PostgreSQL from P&T to comp-functions
  .gitignore
  component/class/defaults.yml
  component/component/vshn_postgres.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/20_role_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  package/main.yaml
  tests/e2e/postgresql/00-assert.yaml
  tests/e2e/postgresql/03-assert.yaml
  tests/e2e/postgresql/05-assert.yaml
  tests/e2e/postgresql/07-assert.yaml
Labels: enhancement

#383 Bump appcat version that fixes a bug in the restore copy job
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: dependency

#382 Update provider kubernetes api objects
  .gitignore
  component/component/prometheus.libsonnet
  component/lib/appcat-compositions.libsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: bug

#384 Update Apiserver image tag
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: bug

#385 Explicitly specify readiness checks
  component/component/common.libsonnet
  component/component/exoscale_kafka.jsonnet
  component/component/exoscale_mysql.jsonnet
  component/component/exoscale_opensearch.jsonnet
  component/component/exoscale_postgres.jsonnet
  component/component/exoscale_redis.jsonnet
  component/tests/golden/cloudscale/appcat/appcat/21_composition_objectstorage_cloudscale.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_kafka.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_mysql.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_opensearch.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_postgres.yaml
  component/tests/golden/exoscale/appcat/appcat/21_composition_exoscale_redis.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_exoscale_kafka.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_exoscale_mysql.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_exoscale_opensearch.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_exoscale_postgres.yaml
  component/tests/golden/openshift/appcat/appcat/21_composition_exoscale_redis.yaml
Labels: bug

#386 Bump appcat version to fix bug in SgPostgresConfigStatus
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
Labels: dependency

#387 Escape invalid object names
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement

#388 Escape the names of generated secrets
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#389 Apply default quotas to all services
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#391 Update apiserver dependency
  component/class/defaults.yml
  component/component/appcat_apiserver.jsonnet
  component/tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/10_cluster_role_view.yaml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/10_cluster_role_view.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_api_server.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/10_cluster_role_view.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: dependency

#393 Update apiserver dependency
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
Labels: dependency
