Repository vshn/component-appcat, pull requests merged in 2024-09, with the labels that each got.

#482 Fix pdb and few inconsistencies in component-appcat
  .gitignore
  Makefile
  class/defaults.yml
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/10_function_appcat.yaml
  tests/golden/billing/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug, patch

#486 Add diff script for compositon functions
  class/appcat.yml
  class/defaults.yml
  component/rbac_e2e.jsonnet
  component/rbac_testing.jsonnet
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/10_function_appcat.yaml
  tests/golden/billing/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: minor

#487 Sane Opsgenie alerting
  component/slos.libsonnet
  component/vshn_alerting.jsonnet
  component/vshn_appcat_services.jsonnet
  component/vshn_minio.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/minio/appcat/appcat/sli_exporter/90_minio_Opsgenie.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/90_slo_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/90_slo_vshn_minio_ha.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_slo_vshn_redis_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_keycloak_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_mariadb_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_nextcloud_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_keycloak_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_mariadb_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_nextcloud_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_postgresql_ha.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_slo_vshn_redis_ha.yaml
Labels: enhancement

#496 Bump appcat version
  class/defaults.yml
  component/vshn_alerting.jsonnet
  tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  tests/golden/apiserver/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/10_function_appcat.yaml
  tests/golden/billing/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/billing/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/cloudscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  tests/golden/controllers/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  tests/golden/exoscale/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/minio/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/90_minio_Opsgenie.yaml
  tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/openshift/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/openshift/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_keycloak_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_mariadb_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/90_nextcloud_Opsgenie.yaml
  tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement
