Repository vshn/component-appcat, pull requests merged in 2024-05, with the labels that each got.

#354 Fix another typo in helmpatcher
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#355 Pass through loadbalancer annotations
  component/class/defaults.yml
  component/component/vshn_postgres.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/vshn.yml
  docs/modules/ROOT/pages/references/services-vshn.adoc
Labels: enhancement

#353 Manage netpol in postgres
  component/class/defaults.yml
  component/component/vshn_minio.jsonnet
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/20_xrd_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  docs/modules/ROOT/pages/references/services-vshn.adoc
  package/main.yaml
Labels: enhancement

#357 Clean up NetworkPolicies
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
Labels: change

#359 Bump billing collector version
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency

#361 Fix E2E tests on Openshift
  component/component/rbac_e2e.jsonnet
Labels: bug

#362 treat OKE like Openshift4
  component/component/appcat_sli_exporter.jsonnet
  component/component/exoscale_kafka.jsonnet
  component/component/exoscale_mysql.jsonnet
  component/component/exoscale_opensearch.jsonnet
  component/component/exoscale_postgres.jsonnet
  component/component/exoscale_redis.jsonnet
  component/component/main.jsonnet
  component/component/vshn_appcat_services.jsonnet
  component/component/vshn_minio.jsonnet
  component/component/vshn_postgres.jsonnet
  component/component/vshn_redis.jsonnet
  package/main.yaml
Labels: enhancement

#364 Add support for Keycloak HA
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: dependency

#366 Fix maintenance wrong tags
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#367 Don't override pg settings
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#368 Add Keycloak&Mariadb alerting, non-sla rules
  .githooks/pre-commit
  component/Makefile
  component/class/defaults.yml
  component/component/vshn_appcat_services.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_exoscale.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_mailgun_secret.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_exoscale.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/10_mailgun_secret.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/minio.yml
  component/tests/vshn.yml
  package/main.yaml
Labels: enhancement

#371 Add usermanagement for PostgreSQL
  component/class/defaults.yml
  component/component/provider.jsonnet
  component/tests/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/apiserver/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/exoscale/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/openshift/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_kubernetes.yaml
  component/tests/golden/vshn/appcat/appcat/10_provider_sql.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/20_xrd_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_keycloak.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: enhancement
