Repository vshn/component-appcat, pull requests merged in 2024-01, with the labels that each got.

#295 Bump appuio-reporting version
  component/class/defaults.yml
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
Labels: dependency

#297 Remove connection secret
  component/class/defaults.yml
  component/component/vshn_redis.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/billing/10_odoo_secret.yaml
  component/tests/golden/vshn/appcat/appcat/billing/11_backfill.yaml
  component/tests/golden/vshn/appcat/appcat/billing/50_alerts.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  package/main.yaml
Labels: enhancement

#300 Bump appcat version for node-selector support for MariaDB
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: dependency

#301 Add manual restore docs for MariaDB
  Makefile
  docs/antora-preview.mk
  docs/modules/ROOT/pages/how-tos/manual-restore-mariadb.adoc
  docs/modules/ROOT/pages/how-tos/redisrestore.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#302 Bump AppCat
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: dependency

#305 Bump billiing-collector version
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency

#306 Bump billing-collector version
  component/class/defaults.yml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: bug, dependency

#307 Remove secret observation
  component/class/defaults.yml
  component/component/vshn_postgres.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#312 Bump appcat
  component/class/defaults.yml
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  package/main.yaml
Labels: bug

#311 Add stackgres operator to component
  component/class/defaults.yml
  component/component/vshn_postgres.jsonnet
  component/tests/golden/apiserver/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/cloudscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/cloudscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/controllers/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/exoscale-metrics-collector-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/exoscale/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/minio/appcat/appcat/21_composition_vshn_minio.yaml
  component/tests/golden/minio/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/minio/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/minio/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/openshift/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/openshift/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/golden/vshn/appcat/appcat/10_function_appcat.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_mariadb.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgres.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_postgresrestore.yaml
  component/tests/golden/vshn/appcat/appcat/21_composition_vshn_redis.yaml
  component/tests/golden/vshn/appcat/appcat/controllers/appcat/30_deployment.yaml
  component/tests/golden/vshn/appcat/appcat/sla_reporter/01_cronjob.yaml
  component/tests/golden/vshn/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  component/tests/vshn.yml
  package/main.yaml
Labels: enhancement
