Repository vshn/component-appcat, pull requests merged in 2024-12, with the labels that each got.

#562 Fix XVSHNPostgeSQL TLS settings in XRD
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_function_appcat.yaml
  tests/golden/control-plane/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/control-plane/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/control-plane/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/dev/appcat/appcat/10_function_appcat.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/dev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/dev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/dev/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/service-cluster/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-cloud/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-managed/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: minor

#565 increasing default max-reconciliation rate for provider-kubernetes
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/dev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_kubernetes.yaml
Labels: enhancement

#568 Fix wrongly rolled out branch
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_function_appcat.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/control-plane/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/control-plane/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/dev/appcat/appcat/10_function_appcat.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/dev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/dev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/dev/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/service-cluster/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: bug

#569 Match serviceLevel of Appcats to corresponding level of a cluster
  component/vshn_appcat_services.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  component/xrds.libsonnet
  tests/control-plane.yml
  tests/defaults.yml
  tests/dev.yml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_keycloak.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_mariadb.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_nextcloud.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_redis.yaml
  tests/service-cluster.yml
  tests/vshn-cloud.yml
  tests/vshn-managed.yml
Labels: enhancement

#572 Fix wrong Nextcloud claim in e2e test
  tests/e2e/nextcloud/00-install.yaml
  tests/e2e/nextcloud/04-install.yaml
Labels: patch
