Repository vshn/component-appcat, pull requests merged in 2025-02, with the labels that each got.

#624 Update resource limits cluster-controller stackgres
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/20_plans_vshn_postgresql.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_postgres.yaml
Labels: patch

#626 Update provider-exoscale to latest version
  class/defaults.yml
  tests/golden/exodev/appcat/appcat/10_provider_exoscale.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_exoscale.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_exoscale.yaml
Labels: dependency

#625 Fix SLA alert name
  component/vshn_alerting.jsonnet
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
Labels: patch

#633 Fix RepeatedResourceWarning for SLA PrometheusRules
  component/prometheus.libsonnet
  component/vshn_alerting.jsonnet
  component/vshn_appcat_services.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_forgejo.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNForgejo_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_forgejo.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNForgejo_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_forgejo.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNForgejo_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_forgejo.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNForgejo_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNPostgreSQL_Opsgenie.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/90_VSHNRedis_Opsgenie.yaml
Labels: bug

#641 Bump provider kubernetes to v0.17.0
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/dev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exodev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_kubernetes.yaml
Labels: dependency

#645 Bump billing collector
  class/defaults.yml
  tests/golden/vshn-cloud/appcat/appcat/cloud_billing/10_exoscale_dbaas_exporter.yaml
  tests/golden/vshn-cloud/appcat/appcat/cloud_billing/20_cloudscale_exporter.yaml
  tests/golden/vshn-cloud/appcat/appcat/cloud_billing/20_exoscale_object_storage_exporter.yaml
Labels: dependency
