Repository vshn/component-appcat, pull requests merged in 2025-06, with the labels that each got.

#748 Remove minio provider config
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/dev/appcat/appcat/10_function_appcat.yaml
  tests/golden/exodev/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-managed/appcat/appcat/10_function_appcat.yaml
Labels: patch

#760 Add autotagging on merge to master
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr.yaml
  tests/golden/control-plane/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/dev/appcat/appcat/10_function_appcat.yaml
  tests/golden/exodev/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-managed/appcat/appcat/10_function_appcat.yaml
Labels: patch

#771 Fix pending annotation issues
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_provider_helm.yaml
  tests/golden/control-plane/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/dev/appcat/appcat/10_provider_helm.yaml
  tests/golden/dev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exodev/appcat/appcat/10_provider_helm.yaml
  tests/golden/exodev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_helm.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_helm.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_kubernetes.yaml
Labels: minor

#701 Add VSHNMinio alerts
  component/vshn_minio.jsonnet
  hack/versionlist
  tests/dev.yml
  tests/golden/dev/appcat/appcat/10_appcat_backup_monitoring.yaml
  tests/golden/dev/appcat/appcat/10_appcat_ha_monitoring.yaml
  tests/golden/dev/appcat/appcat/20_plans_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/20_rbac_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/22_minio_instances.yaml
  tests/golden/dev/appcat/appcat/22_minio_prometheus_rule.yaml
  tests/golden/dev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/dev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/70_slo_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/80_slo_vshn_minio_ha.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_minio_prometheus_rule.yaml
  tests/golden/vshn-managed/appcat/appcat/22_minio_prometheus_rule.yaml
Labels: enhancement

#794 Revert/minio alerting
  component/vshn_minio.jsonnet
  hack/versionlist
  tests/dev.yml
  tests/golden/dev/appcat/appcat/10_appcat_backup_monitoring.yaml
  tests/golden/dev/appcat/appcat/10_appcat_ha_monitoring.yaml
  tests/golden/dev/appcat/appcat/20_plans_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/20_rbac_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/20_xrd_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/22_minio_instances.yaml
  tests/golden/dev/appcat/appcat/22_minio_prometheus_rule.yaml
  tests/golden/dev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/dev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/70_slo_vshn_minio.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/80_slo_vshn_minio_ha.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/vshn-cloud/appcat/appcat/22_minio_prometheus_rule.yaml
  tests/golden/vshn-managed/appcat/appcat/22_minio_prometheus_rule.yaml
Labels: patch
