Repository vshn/component-appcat, pull requests merged in 2025-01, with the labels that each got.

#589 Distinct name for the ArgoCD app
  Makefile
Labels: patch

#590 Remove maintenance e2e tests
  tests/e2e/postgresql/100-assert.yaml
  tests/e2e/postgresql/100-connect.yaml
  tests/e2e/postgresql/100-install.yaml
  tests/e2e/postgresql/110-assert.yaml
  tests/e2e/postgresql/110-install.yaml
  tests/e2e/postgresql/30-assert.yaml
  tests/e2e/postgresql/30-install.yaml
  tests/e2e/postgresql/30-validate.yaml
  tests/e2e/postgresql/40-assert.yaml
  tests/e2e/postgresql/40-install.yaml
  tests/e2e/postgresql/50-validate.yaml
  tests/e2e/postgresql/60-assert.yaml
  tests/e2e/postgresql/70-validate.yaml
  tests/e2e/postgresql/80-assert.yaml.yaml
  tests/e2e/postgresql/80-install.yaml
Labels: patch

#597 restoring SLO targets rules on Exoscale clusters
  component/vshn_appcat_services.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/vshn-managed.yml
Labels: bug

#600 Bump provider kubernetes
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/dev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/exodev/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_provider_kubernetes.yaml
  tests/golden/vshn-managed/appcat/appcat/10_provider_kubernetes.yaml
Labels: patch

#601 Fix oc image repo
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_nextcloud.yaml
Labels: patch

#603 Disable prometheus rules if slos is disabled
  component/vshn_appcat_services.jsonnet
  component/vshn_postgres.jsonnet
  component/vshn_redis.jsonnet
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/defaults/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/90_VSHNKeycloak_Opsgenie.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/90_VSHNMariaDB_Opsgenie.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/90_VSHNNextcloud_Opsgenie.yaml
  tests/golden/dev/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_keycloak.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_mariadb.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_nextcloud.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_postgres.yaml
  tests/golden/exodev/appcat/appcat/22_prom_rule_sla_redis.yaml
  tests/golden/service-cluster/appcat/appcat/22_prom_rule_sla_minio.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/90_VSHNMinio_Opsgenie.yaml
Labels: patch

#610 bump appcat version
  class/defaults.yml
  tests/golden/control-plane/appcat/appcat/10_function_appcat.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/control-plane/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/control-plane/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/control-plane/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/defaults/appcat/appcat/10_function_appcat.yaml
  tests/golden/defaults/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/defaults/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/dev/appcat/appcat/10_function_appcat.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/dev/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/dev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/dev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/dev/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/dev/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/exodev/appcat/appcat/10_function_appcat.yaml
  tests/golden/exodev/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/exodev/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/exodev/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/service-cluster/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/service-cluster/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn-cloud/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-cloud/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-cloud/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-cloud/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-cloud/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
  tests/golden/vshn-managed/appcat/appcat/10_function_appcat.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_keycloak.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_mariadb.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_minio.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_nextcloud.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_postgres.yaml
  tests/golden/vshn-managed/appcat/appcat/21_composition_vshn_redis.yaml
  tests/golden/vshn-managed/appcat/appcat/apiserver/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/controllers/appcat/30_deployment.yaml
  tests/golden/vshn-managed/appcat/appcat/sla_reporter/01_cronjob.yaml
  tests/golden/vshn-managed/appcat/appcat/sli_exporter/apps_v1_deployment_appcat-sliexporter-controller-manager.yaml
Labels: enhancement
